In [1]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [2]:
import cv2
import numpy as np

In [3]:
# Load an image using 'imread' specifying the path to image
img = cv2.imread('D:\\Data Science by SRK\\Deep Learning\\images\\tiger.JPG',1)


In [4]:
print(img)

[[[ 10  33 119]
  [  0  21 107]
  [ 18  38 126]
  ...
  [ 12  27  73]
  [ 16  32  75]
  [ 24  40  83]]

 [[ 12  35 121]
  [  0  19 105]
  [ 11  31 119]
  ...
  [ 24  39  85]
  [ 12  27  73]
  [  4  20  63]]

 [[ 18  39 124]
  [  0  20 105]
  [  4  24 111]
  ...
  [ 11  25  73]
  [  9  23  71]
  [ 14  29  75]]

 ...

 [[215 214 223]
  [215 214 223]
  [216 215 224]
  ...
  [197 218 226]
  [196 218 230]
  [191 212 227]]

 [[215 214 223]
  [216 215 224]
  [216 215 224]
  ...
  [195 216 224]
  [197 219 231]
  [190 212 224]]

 [[214 213 222]
  [214 213 222]
  [215 214 223]
  ...
  [196 217 225]
  [200 222 233]
  [194 216 228]]]


Shape gives the dimensions of the image array

In [5]:
img.shape

# The 3D dimensions are 720 pixels in height *(multiply by) 480 pixels width
# 3 means that there are 3 components(combination of RGB colors) that make up image 
# (3 means the image is 3D array ehich means the image is colourful image)

(720, 480, 3)

# Display the image

In [6]:
# To display our image variable, we use 'imshow' function
# The 1st parameter in imshow function is the title shown on image window
# The 2nd parameter in imshow function will is the image loaded variable(i.e here img)

cv2.imshow('tiger',img)


# 'waitKey()' function allows us to input information when a image window is open 
    # if we give waitkey() function without parameter then it will wait the image window untill we press any key on keyboard
    # if we give waitkey(2000) function with parameter then it will wait the image window upto the given time will not complete(here time is in miliseconds)
    
cv2.waitKey(2000)


# destroyAllWindows() function closes all open windows
# If we not write destroyAllWindows() function, then our program can be hang

cv2.destroyAllWindows()

In [7]:
#img = cv2.imread('D:\\Data Science by SRK\\Deep Learning\\images\\tiger.JPG',1)
#cv2.imshow('tiger', img)
#cv2.waitKey()
#cv2.destroyAllWindows()


In [8]:
# 'imwrite()' used to specificing the file name and save the image in current working directory

cv2.imwrite('tiger_b_w.jpg', img)   # It will save the image in current working directory with the name as 'tiger_b_w.jpg'.

True

# Resize Image

In [9]:
img = cv2.imread('D:\\Data Science by SRK\\Deep Learning\\images\\tiger.JPG')

resized_image = cv2.resize(img,(400,400))  # ---> here the color image will resized into the given size of image.

gray = cv2.cvtColor(resized_image, cv2.COLOR_BGR2GRAY)   # here the color image will convert (or display) into the black & white image which will be the 2D-array

cv2.imshow('Tiger Image', gray)

cv2.waitKey()
cv2.destroyAllWindows()


# Note:-
       # This shell will continouely run untill we externally exit the image window(means we have press the exit(any key) to exit from the image window then only this shell will stop running)

In [10]:
img.shape[0]*0.5

360.0

In [11]:
img.shape[1]*0.5

240.0

# Face Detection using HAAR Cascade Classifier

     Note :- 
               To use the HAAR Casacde Classifier files we have to first download that files and save them into the current                working directory otherwise it will not work(it will give error). 
           
                means  eg.  - To use the 'haarcascade_frontalface_default.xml' & 'haarcascade_eye.xml' files to detect                      face(s) and eye(s) resp. Firstly we have to download them and save them into the current working directory.

In [12]:
# we point OpenCV'S CascadeClassifier function to where our classifier(in .xml file format) is stored
# The CascadeClassifier will stores all types of sketches to detection of related objects from the images
    # The HAAR Cascade Classifier is developed by the software developer which stores the stores the all types sketches in it in the .xml file format 
face_classifier = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')  # Here this will load the frontalface i.e. face related sketeches on the machine to detect the face(s) from the given image

# Load our image then convert it into the grayscale image(means into black & white image)
image = cv2.imread('D:\\Data Science by SRK\\Deep Learning\\images\\tiger.JPG')
# image = cv2.resize(image,(400,400))
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

### Tuning Cascade Classifiers - detectMultiScale(input image, **Scale Factor**, **Min Neighbors**) \
faces = face_classifier.detectMultiScale(gray, 1.05, 5)   # ---> Here, this function is used to detect the face from the given input image by reducing the size of image each time(i.e. here it will reduce the size by 5%(1.05) each time)
                                                              # and also this function will not check the face in exact location of face in image it will try to match the features of face with all the given no. of neighbors in image
                                                              # (i.e. it will try to match the features(steches) with the given no. of neighbors pixels in the given image)
 


# **Scale Factor** - It specifies how much we reduce the image size each time we scale(i.e. means while matching the steches(features) how much the size of image we reduce to detect the face in the image)
                    # that means to detect the face from the image the machine will not check line by line that the features from cascade classifier are matching with image small part(i.e.pixel) or not that means it will match the features by reducing overall size of image each time untill the face detection.
    # eg. in face detection we typically use 1.3. This means we reduce the image size by 30% each time of it's total size.
    # The smaller value of scale factor like 1.05 will take longer time to compute(to give result), it will give high accuracy(increse the rate of detection).
    

# **Min Neighbors** - It speciefies the no. of neighbors each potential window should have in order to consider it a positive detection(i.e. means while detecting the face in the image the machine will check the face in the given no. of neighbors from the face detected location in the image)
# typically we use 3-6 no. of neighbors.
# It acts as sensitivity setting, if no. of neighbors are less then it will sometimes detect multiples faces over a single face.
                                # if no. of neighbors are high then it will ensure less false positives(less error), but you may miss some faces to detect from image.
    
        

In [13]:
print(faces)

[[100  76 244 244]]


In [14]:
# we point OpenCV'S CascadeClassifier function to where our classifier(in .xml file format) is stored
# The CascadeClassifier will stores all types of sketches to detection of related objects from the images
    # The HAAR Cascade Classifier is developed by the software developer which stores the stores the all types sketches in it in the .xml file format 
face_classifier = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')  # Here this will load the frontalface i.e. face related sketeches on the machine to detect the face(s) from the given image

# Load our image then convert it into the grayscale image(means into black & white image)
image = cv2.imread('D:\\Data Science by SRK\\Deep Learning\\images\\tiger.JPG')
image = cv2.resize(image,(400,400))
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

### Tuning Cascade Classifiers - detectMultiScale(input image, **Scale Factor**, **Min Neighbors**) \
faces = face_classifier.detectMultiScale(gray, 1.05, 5)   # ---> Here, this function is used to detect the face from the given input image by reducing the size of image each time(i.e. here it will reduce the size by 5%(1.05) each time)
                                                              # and also this function will not check the face in exact location of face in image it will try to match the features of face with all the given no. of neighbors in image
                                                              # (i.e. it will try to match the features(steches) with the given no. of neighbors pixels in the given image)
 


# **Scale Factor** - It specifies how much we reduce the image size each time we scale(i.e. means while matching the steches(features) how much the size of image we reduce to detect the face in the image)
                    # that means to detect the face from the image the machine will not check line by line that the features from cascade classifier are matching with image small part(i.e.pixel) or not that means it will match the features by reducing overall size of image each time untill the face detection.
    # eg. in face detection we typically use 1.3. This means we reduce the image size by 30% each time of it's total size.
    # The smaller value of scale factor like 1.05 will take longer time to compute(to give result), it will give high accuracy(increse the rate of detection).
    

# **Min Neighbors** - It speciefies the no. of neighbors each potential window should have in order to consider it a positive detection(i.e. means while detecting the face in the image the machine will check the face in the given no. of neighbors from the face detected location in the image)
# typically we use 3-6 no. of neighbors.
# It acts as sensitivity setting, if no. of neighbors are less then it will sometimes detect multiples faces over a single face.
                                # if no. of neighbors are high then it will ensure less false positives(less error), but you may miss some faces to detect from image.
    

# When no faces are detected, then face_classifier returns an empty tuple
if faces is ():
    print("No faces found")
    
# We iterate through our faces array and draw a rectangle over each face in faces from images
for (x,y,w,h) in faces:
    cv2.rectangle(image, (x,y), (x+w,y+h), (0,255,100), 1)   # It will draw the rectangle box on the detected faces from image
    
cv2.imshow('Face Detection', image)
cv2.waitKey()
cv2.destroyAllWindows()


<>:31: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:31: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\Dell\AppData\Local\Temp\ipykernel_1888\2338786775.py:31: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


# Face & Eye Detection using HAAR Cascade Classifiers in Image

In [15]:
face_classifier = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
eye_classifier = cv2.CascadeClassifier('haarcascade_eye.xml')  # Here this will load the eye i.e.eye related sketeches on the machine to detect the eye(s) from the given image

img = cv2.imread('D:\\Data Science by SRK\\Deep Learning\\images\\sky.webp')
resized_img = cv2.resize(img,(720,720))
gray = cv2.cvtColor(resized_img, cv2.COLOR_BGR2GRAY)

faces = face_classifier.detectMultiScale(gray, 1.3, 5)

# When no face is detected , then face_classifier will returns an empty tuple
if faces is ():
    print("No face found...")
    
for (x,y,w,h) in faces:
    cv2.rectangle(resized_img, (x,y), (x+w,y+h), (255,0,0), 2)
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = resized_img[y:y+h, x:x+w]
    eyes = eye_classifier.detectMultiScale(roi_gray)
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
        
cv2.imshow('img',resized_img)
cv2.waitKey()
cv2.destroyAllWindows()

<>:11: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:11: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\Dell\AppData\Local\Temp\ipykernel_1888\1571546015.py:11: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


# Capturing a video by Webcam

In [16]:
# Doing some Face Recognition(detection) with the webcam(live video)

import cv2
video = cv2.VideoCapture(0)  # Here, 0 means webcam

while True:
    check, frame = video.read()
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow('Video', gray)
    if cv2.waitKey(1) == ord('q'):
        break
        
video.release()
cv2.destroyAllWindows()

# Face & Eye Detection using HAAR Cascade Classifiers in Webcam(live Video)

In [17]:
# Defining a function that will do the face detection in webcam
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('haarcascade_eye.xml')

def detect(gray, frame):
    faces = face_cascade.detectMultiScale(gray,1.05,5)
    for (x,y,w,h) in faces:
        cv2.rectangle(resized_img, (x,y), (x+w,y+h), (255,0,0), 2)
        roi_gray = gray[y:y+h, x:x+w]
        roi_color = frame[y:y+h, x:x+w]
        eyes = eye_cascade.detectMultiScale(roi_gray, 1.3, 3)
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
    return frame

# Doing some face recognition with webcame
video = cv2.VideoCapture(0)

while True:
    check, frame = video.read()
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    canvas = detect(gray,frame)
    cv2.imshow('Video', canvas)
    if cv2.waitKey(1) == ord('q'):
        break
        
video.release()
cv2.destroyAllWindows()

# Pedistrian Detection

In [18]:
import cv2

# Create our body classifier
body_classifier = cv2.CascadeClassifier('haarcascade_fullbody.xml')   # Here this will load the human body related sketeches on the machine to detect the human bodies from the given video(multiple images)

# Initiate video capture for video file
cap = cv2.VideoCapture('walking.avi')    # Here this will load the already recorded video on the machine to detect the human bodies.

# loop once video is successfully loaded
while cap.isOpened():
    # Read first frame
    check, frame = cap.read()    # It will capture the first frame from the video and forward it to check(match) the sketches of cars with it. (and using while loop this will continuely cature frame untill video ends.)
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    
    # Pass frame to our body classifier
    bodies = body_classifier.detectMultiScale(gray, 1.2, 3)
    
    # Extract bounding boxes for any bodies indentified
    for (x,y,w,h) in bodies:
        cv2.rectangle(frame, (x,y), (x+w, y+h), (0,255,255), 2)
        cv2.imshow('Podestrians', frame)
        
    if cv2.waitKey(1)==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()


In [19]:
import time
import cv2


# Create our body classifier 
car_classifier = cv2.CascadeClassifier('haarcascade_car.xml')   # Here this will load the car related sketeches on the machine to detect the car(s) from the given video(multiple images)

#Initiate video capture for video file
cap = cv2.VideoCapture('cars.avi')  # Here this will load the already recorded video on the machine to detect the car(s).


# loop once video is successfully loaded
while cap.isOpened():
    
    time.sleep(0.05)   # This will make the speed of video slow as per given value in 'sleep()' function
    
    # Read first frame
    check, frame = cap.read()     # It will capture the first frame from the video and forward it to check(match) the sketches of cars with it. (and using while loop this will continuely capture frame untill video ends.)
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    # Pass frame to car(s) classifier
    cars = car_classifier.detectMultiScale(gray, 1.4, 2)
    
    # Extract bounding boxes for any car(s) indentified
    for (x,y,w,h) in cars:
        cv2.rectangle(frame, (x,y), (x+w, y+h), (0,255,255), 2)
        cv2.imshow('Cars', frame)
        
    if cv2.waitKey(1)==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()
    